//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laser.Orchard.Mobile.SmsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sms", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Mobile.SmsServiceReference.ArrayOfLong SmsNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        private int SmsValidityPeriodField;
        
        private int SmsProrityField;
        
        private int SmsTipoCodificaField;
        
        private bool MamHaveAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsFromField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Laser.Orchard.Mobile.SmsServiceReference.ArrayOfLong SmsNumber {
            get {
                return this.SmsNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsNumberField, value) != true)) {
                    this.SmsNumberField = value;
                    this.RaisePropertyChanged("SmsNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmsBody {
            get {
                return this.SmsBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsBodyField, value) != true)) {
                    this.SmsBodyField = value;
                    this.RaisePropertyChanged("SmsBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverIdField, value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SmsValidityPeriod {
            get {
                return this.SmsValidityPeriodField;
            }
            set {
                if ((this.SmsValidityPeriodField.Equals(value) != true)) {
                    this.SmsValidityPeriodField = value;
                    this.RaisePropertyChanged("SmsValidityPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SmsPrority {
            get {
                return this.SmsProrityField;
            }
            set {
                if ((this.SmsProrityField.Equals(value) != true)) {
                    this.SmsProrityField = value;
                    this.RaisePropertyChanged("SmsPrority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int SmsTipoCodifica {
            get {
                return this.SmsTipoCodificaField;
            }
            set {
                if ((this.SmsTipoCodificaField.Equals(value) != true)) {
                    this.SmsTipoCodificaField = value;
                    this.RaisePropertyChanged("SmsTipoCodifica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool MamHaveAlias {
            get {
                return this.MamHaveAliasField;
            }
            set {
                if ((this.MamHaveAliasField.Equals(value) != true)) {
                    this.MamHaveAliasField = value;
                    this.RaisePropertyChanged("MamHaveAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SmsFrom {
            get {
                return this.SmsFromField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsFromField, value) != true)) {
                    this.SmsFromField = value;
                    this.RaisePropertyChanged("SmsFrom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    [System.SerializableAttribute()]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusByExtId", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StatusByExtId : Laser.Orchard.Mobile.SmsServiceReference.SmsStatus {
        
        private long SmsNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long SmsNumber {
            get {
                return this.SmsNumberField;
            }
            set {
                if ((this.SmsNumberField.Equals(value) != true)) {
                    this.SmsNumberField = value;
                    this.RaisePropertyChanged("SmsNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsStatus", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laser.Orchard.Mobile.SmsServiceReference.StatusByNum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId))]
    public partial class SmsStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsSentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsLastUpdateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SmsState {
            get {
                return this.SmsStateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsStateField, value) != true)) {
                    this.SmsStateField = value;
                    this.RaisePropertyChanged("SmsState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SmsSentDate {
            get {
                return this.SmsSentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsSentDateField, value) != true)) {
                    this.SmsSentDateField = value;
                    this.RaisePropertyChanged("SmsSentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SmsLastUpdate {
            get {
                return this.SmsLastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsLastUpdateField, value) != true)) {
                    this.SmsLastUpdateField = value;
                    this.RaisePropertyChanged("SmsLastUpdate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusByNum", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class StatusByNum : Laser.Orchard.Mobile.SmsServiceReference.SmsStatus {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.SmsServiceSoap")]
    public interface SmsServiceSoap {
        
        // CODEGEN: Generating message contract since element name sms from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse SendSMS(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name externalId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateByExternalId", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse GetSmsStateByExternalId(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateByExternalId", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> GetSmsStateByExternalIdAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetSmsStateBySmsNumberResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateBySmsNumber", ReplyAction="*")]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse GetSmsStateBySmsNumber(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsStateBySmsNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse> GetSmsStateBySmsNumberAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.Sms sms;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(Laser.Orchard.Mobile.SmsServiceReference.Sms sms) {
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateByExternalIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateByExternalId", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody Body;
        
        public GetSmsStateByExternalIdRequest() {
        }
        
        public GetSmsStateByExternalIdRequest(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateByExternalIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string externalId;
        
        public GetSmsStateByExternalIdRequestBody() {
        }
        
        public GetSmsStateByExternalIdRequestBody(string externalId) {
            this.externalId = externalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateByExternalIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateByExternalIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponseBody Body;
        
        public GetSmsStateByExternalIdResponse() {
        }
        
        public GetSmsStateByExternalIdResponse(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateByExternalIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalIdResult;
        
        public GetSmsStateByExternalIdResponseBody() {
        }
        
        public GetSmsStateByExternalIdResponseBody(Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalIdResult) {
            this.GetSmsStateByExternalIdResult = GetSmsStateByExternalIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateBySmsNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateBySmsNumber", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequestBody Body;
        
        public GetSmsStateBySmsNumberRequest() {
        }
        
        public GetSmsStateBySmsNumberRequest(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateBySmsNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long smsNumber;
        
        public GetSmsStateBySmsNumberRequestBody() {
        }
        
        public GetSmsStateBySmsNumberRequestBody(long smsNumber) {
            this.smsNumber = smsNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSmsStateBySmsNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSmsStateBySmsNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponseBody Body;
        
        public GetSmsStateBySmsNumberResponse() {
        }
        
        public GetSmsStateBySmsNumberResponse(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSmsStateBySmsNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByNum[] GetSmsStateBySmsNumberResult;
        
        public GetSmsStateBySmsNumberResponseBody() {
        }
        
        public GetSmsStateBySmsNumberResponseBody(Laser.Orchard.Mobile.SmsServiceReference.StatusByNum[] GetSmsStateBySmsNumberResult) {
            this.GetSmsStateBySmsNumberResult = GetSmsStateBySmsNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsServiceSoapChannel : Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceSoapClient : System.ServiceModel.ClientBase<Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap>, Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap {
        
        public SmsServiceSoapClient() {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.SendSMS(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(Laser.Orchard.Mobile.SmsServiceReference.Sms sms) {
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody();
            inValue.Body.sms = sms;
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.SendSMSResponse> SendSMSAsync(Laser.Orchard.Mobile.SmsServiceReference.Sms sms) {
            Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.SendSMSRequestBody();
            inValue.Body.sms = sms;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.GetSmsStateByExternalId(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request) {
            return base.Channel.GetSmsStateByExternalId(request);
        }
        
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByExtId[] GetSmsStateByExternalId(string externalId) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody();
            inValue.Body.externalId = externalId;
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).GetSmsStateByExternalId(inValue);
            return retVal.Body.GetSmsStateByExternalIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.GetSmsStateByExternalIdAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest request) {
            return base.Channel.GetSmsStateByExternalIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdResponse> GetSmsStateByExternalIdAsync(string externalId) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateByExternalIdRequestBody();
            inValue.Body.externalId = externalId;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).GetSmsStateByExternalIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.GetSmsStateBySmsNumber(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest request) {
            return base.Channel.GetSmsStateBySmsNumber(request);
        }
        
        public Laser.Orchard.Mobile.SmsServiceReference.StatusByNum[] GetSmsStateBySmsNumber(long smsNumber) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequestBody();
            inValue.Body.smsNumber = smsNumber;
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse retVal = ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).GetSmsStateBySmsNumber(inValue);
            return retVal.Body.GetSmsStateBySmsNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse> Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap.GetSmsStateBySmsNumberAsync(Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest request) {
            return base.Channel.GetSmsStateBySmsNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberResponse> GetSmsStateBySmsNumberAsync(long smsNumber) {
            Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest inValue = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequest();
            inValue.Body = new Laser.Orchard.Mobile.SmsServiceReference.GetSmsStateBySmsNumberRequestBody();
            inValue.Body.smsNumber = smsNumber;
            return ((Laser.Orchard.Mobile.SmsServiceReference.SmsServiceSoap)(this)).GetSmsStateBySmsNumberAsync(inValue);
        }
    }
}
