//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laser.Orchard.Queues.wsCode {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatoRichiesta", Namespace="http://schemas.datacontract.org/2004/07/WcfCoda")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laser.Orchard.Queues.wsCode.CodaAttuale))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Laser.Orchard.Queues.wsCode.CodeElenco))]
    public partial class StatoRichiesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Queues.wsCode.ErroreRichiesta[] ErroriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Laser.Orchard.Queues.wsCode.ErroreRichiesta[] Errori {
            get {
                return this.ErroriField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroriField, value) != true)) {
                    this.ErroriField = value;
                    this.RaisePropertyChanged("Errori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodaAttuale", Namespace="http://schemas.datacontract.org/2004/07/WcfCoda")]
    [System.SerializableAttribute()]
    public partial class CodaAttuale : Laser.Orchard.Queues.wsCode.StatoRichiesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DescrizioneFuoriLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> DescrizioneStatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PingInLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Queues.wsCode.StatiCoda StatoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contatore {
            get {
                return this.ContatoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoreField, value) != true)) {
                    this.ContatoreField = value;
                    this.RaisePropertyChanged("Contatore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> DescrizioneFuoriLinea {
            get {
                return this.DescrizioneFuoriLineaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneFuoriLineaField, value) != true)) {
                    this.DescrizioneFuoriLineaField = value;
                    this.RaisePropertyChanged("DescrizioneFuoriLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> DescrizioneStato {
            get {
                return this.DescrizioneStatoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneStatoField, value) != true)) {
                    this.DescrizioneStatoField = value;
                    this.RaisePropertyChanged("DescrizioneStato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PingInLinea {
            get {
                return this.PingInLineaField;
            }
            set {
                if ((this.PingInLineaField.Equals(value) != true)) {
                    this.PingInLineaField = value;
                    this.RaisePropertyChanged("PingInLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Laser.Orchard.Queues.wsCode.StatiCoda Stato {
            get {
                return this.StatoField;
            }
            set {
                if ((this.StatoField.Equals(value) != true)) {
                    this.StatoField = value;
                    this.RaisePropertyChanged("Stato");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeElenco", Namespace="http://schemas.datacontract.org/2004/07/WcfCoda")]
    [System.SerializableAttribute()]
    public partial class CodeElenco : Laser.Orchard.Queues.wsCode.StatoRichiesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Laser.Orchard.Queues.wsCode.CodaAttuale[] CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Laser.Orchard.Queues.wsCode.CodaAttuale[] Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroreRichiesta", Namespace="http://schemas.datacontract.org/2004/07/WcfCoda")]
    [System.SerializableAttribute()]
    public partial class ErroreRichiesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErroreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegnalazioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Errore {
            get {
                return this.ErroreField;
            }
            set {
                if ((this.ErroreField.Equals(value) != true)) {
                    this.ErroreField = value;
                    this.RaisePropertyChanged("Errore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Segnalazione {
            get {
                return this.SegnalazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.SegnalazioneField, value) != true)) {
                    this.SegnalazioneField = value;
                    this.RaisePropertyChanged("Segnalazione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatiCoda", Namespace="http://schemas.datacontract.org/2004/07/WcfCoda")]
    public enum StatiCoda : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attivo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonAttivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FuoriLinea = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCode.ICodeGestione")]
    public interface ICodeGestione {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/Imposta", ReplyAction="http://tempuri.org/ICodeGestione/ImpostaResponse")]
        Laser.Orchard.Queues.wsCode.CodeElenco Imposta(Laser.Orchard.Queues.wsCode.CodeElenco c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/Imposta", ReplyAction="http://tempuri.org/ICodeGestione/ImpostaResponse")]
        System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> ImpostaAsync(Laser.Orchard.Queues.wsCode.CodeElenco c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/Leggi", ReplyAction="http://tempuri.org/ICodeGestione/LeggiResponse")]
        Laser.Orchard.Queues.wsCode.CodeElenco Leggi(Laser.Orchard.Queues.wsCode.CodeElenco c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/Leggi", ReplyAction="http://tempuri.org/ICodeGestione/LeggiResponse")]
        System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> LeggiAsync(Laser.Orchard.Queues.wsCode.CodeElenco c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/PingStatoInLinea", ReplyAction="http://tempuri.org/ICodeGestione/PingStatoInLineaResponse")]
        Laser.Orchard.Queues.wsCode.CodeElenco PingStatoInLinea(Laser.Orchard.Queues.wsCode.CodeElenco c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICodeGestione/PingStatoInLinea", ReplyAction="http://tempuri.org/ICodeGestione/PingStatoInLineaResponse")]
        System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> PingStatoInLineaAsync(Laser.Orchard.Queues.wsCode.CodeElenco c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICodeGestioneChannel : Laser.Orchard.Queues.wsCode.ICodeGestione, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodeGestioneClient : System.ServiceModel.ClientBase<Laser.Orchard.Queues.wsCode.ICodeGestione>, Laser.Orchard.Queues.wsCode.ICodeGestione {
        
        public CodeGestioneClient() {
        }
        
        public CodeGestioneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodeGestioneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeGestioneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodeGestioneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Laser.Orchard.Queues.wsCode.CodeElenco Imposta(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.Imposta(c);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> ImpostaAsync(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.ImpostaAsync(c);
        }
        
        public Laser.Orchard.Queues.wsCode.CodeElenco Leggi(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.Leggi(c);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> LeggiAsync(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.LeggiAsync(c);
        }
        
        public Laser.Orchard.Queues.wsCode.CodeElenco PingStatoInLinea(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.PingStatoInLinea(c);
        }
        
        public System.Threading.Tasks.Task<Laser.Orchard.Queues.wsCode.CodeElenco> PingStatoInLineaAsync(Laser.Orchard.Queues.wsCode.CodeElenco c) {
            return base.Channel.PingStatoInLineaAsync(c);
        }
    }
}
